Add adversarial demucs
mosem/denoiser pull request #18
Opened 2021-10-31 12:34 UTC by mosem

2021-11-03 18:07 UTC, Or-Tal commented on denoiser/batch_solvers/generator_bs.py
> -logger = logging.getLogger(__name__)
don't we need this? erasing this explicitly assumes global logger variable

2021-11-03 18:08 UTC, Or-Tal commented on denoiser/models/modules.py
>  import math
see previous pull requests comment regarding this being a very long file

2021-11-03 18:09 UTC, Or-Tal commented on launch_valentini.sh
>  python train.py \
please have a separate .sh file for testing keep this example file with demucs

2021-11-03 18:11 UTC, Or-Tal requested changes
Hi please see my comments , I don't like the adversarial flag it adds a non necessary flag to all of our config files instead of being configuration specific.

2021-11-07 10:02 UTC, mosem commented on denoiser/batch_solvers/generator_bs.py
> -logger = logging.getLogger(__name__)
This was only for debugging purposes.

2021-11-09 09:44 UTC, merged