Add adversarial caunet
mosem/denoiser pull request #19
Opened 2021-10-31 12:34 UTC by mosem

2021-11-03 18:12 UTC, Or-Tal commented on conf/experiment/caunet_1.yaml
> +experiment_name: caunet_1
see prev pull requests

2021-11-03 18:13 UTC, Or-Tal commented on conf/experiment/demucs_1.yaml
> +adversarial: False
see prev pull requests

2021-11-03 18:14 UTC, Or-Tal commented on conf/experiment/example_file.yaml
> -  ndf: 16
what are theses flags? why are they in the general example file? these are configuration specific.

2021-11-03 18:14 UTC, Or-Tal commented on conf/experiment/example_file.yaml
> +  ndf: 16
dido

2021-11-03 18:14 UTC, Or-Tal commented on conf/experiment/example_file.yaml
> +adversarial: False
dido

2021-11-03 18:15 UTC, Or-Tal commented on denoiser/batch_solvers/adversarial_bs.py
> +        self._optimizers.update(({'discriminator_optimizer': disc_optimizer}))
use magic number instead of explicit strings

2021-11-03 18:15 UTC, Or-Tal commented on denoiser/batch_solvers/adversarial_bs.py
> +        self._losses_names += ['discriminator']
dido

2021-11-03 18:15 UTC, Or-Tal commented on denoiser/batch_solvers/adversarial_bs.py
> +        generator = self._models['generator']
magic num instead of explicit string

2021-11-03 18:15 UTC, Or-Tal commented on denoiser/batch_solvers/adversarial_bs.py
> +        generator_optimizer = self._optimizers['generator_optimizer']
magic num instead of explicit string

2021-11-03 18:16 UTC, Or-Tal commented on denoiser/batch_solvers/batch_solver_factory.py
> +        if args.experiment.adversarial:
see prev comment about this redundancy

2021-11-03 18:16 UTC, Or-Tal commented on denoiser/models/modules.py
> -from torch import nn, nn as nn
see prev comment about long file

2021-11-03 18:17 UTC, Or-Tal commented on launch_valentini.sh
see prev comment

2021-11-03 18:19 UTC, Or-Tal requested changes
Hi, using explicit strings is asking for troubles, I think you should replace all strings with magic numbers that are defined in a single point of truth.
Please read the rest of my notes

2021-11-09 11:00 UTC, mosem commented on conf/experiment/example_file.yaml
> -  ndf: 16
I don't see any difference between discriminators and other models, they should be here just like any other model.

2021-11-09 11:25 UTC, mosem reviewed
looks done. merging...

2021-11-09 11:25 UTC, merged