Add skipless demucs 2
mosem/denoiser pull request #30
Opened 2021-11-09 12:07 UTC by mosem

2021-11-18 15:25 UTC, Or-Tal requested changes
Please look into my comments, I have addressed several important issues that you should handle before merging this branch. 
once fixed it could be merged. no need to re-inspect this one.

2021-11-18 15:25 UTC, Or-Tal commented on conf/experiment/demucs_skipless_1.yaml
> +experiment_name: demucs_skipless_1
add # @package experiment in the top line

2021-11-18 15:25 UTC, Or-Tal commented on conf/experiment/demucs_skipless_adversarial_1.yaml
> +experiment_name: demucs_skipless_adversarial_1
add # @Package experiment in the top line

2021-11-18 15:25 UTC, Or-Tal commented on denoiser/models/autoencoder_composer.py
> +        return out
looks good

2021-11-18 15:25 UTC, Or-Tal commented on denoiser/models/autoencoder_composer.py
> +        encoder_output_length = self.encoder.estimate_output_length(input_length)
looks like a good practice to force this API on the modules. (estimate_output_length)

2021-11-18 15:25 UTC, Or-Tal commented on denoiser/models/demucs_encoder.py
> +            return std * x
dividing by the std forces a normalization of the std to match a normal distribution (std=1) yet re-multiplying by std aims to un-normalize the output back to the same distribution. therefore multiplying by std should be done over the output of the ENTIRE network, i.e. in the decoder output.

2021-11-18 15:25 UTC, Or-Tal commented on denoiser/models/demucs_encoder.py
> +            return std * x, skips_signals
dividing by the std forces a normalization of the std to match a normal distribution (std=1) yet re-multiplying by std aims to un-normalize the output back to the same distribution. therefore multiplying by std should be done over the output of the ENTIRE network, i.e. in the decoder output.

2021-11-18 15:25 UTC, Or-Tal commented on test_denoiser.py
>      'demucs_hifi': ['train.py', 'dset=valentini_dummy', 'experiment=demucs_hifi',
I may have missed removing demucs_hifi from this section when I removed it from master, please remove this alongside fixing the above issues and merge into master without this segment

2021-11-18 15:25 UTC, Or-Tal commented on denoiser/models/demucs_decoder.py
> +        if self.normalize:
this should be evalueated over the input to the entire network. I believe the best way to do so is to implement it in the wrapping model, such that normaliation is evaluated over the input and being applied on the input, and then re-multiply the output by std to get an un-normalized result.

2021-11-21 11:29 UTC, mosem commented on denoiser/models/autoencoder_composer.py
> +        encoder_output_length = self.encoder.estimate_output_length(input_length)
I'll do this refactoring in another pull request.

2021-11-21 11:36 UTC, mosem commented on denoiser/models/demucs_encoder.py
> +            return std * x
Not sure I understand this, can you explain this to me when we meet?

2021-11-21 11:36 UTC, mosem commented on conf/experiment/demucs_skipless_1.yaml
> +experiment_name: demucs_skipless_1
done.

2021-11-21 11:36 UTC, mosem commented on denoiser/models/autoencoder_composer.py
> +        return out
done.

2021-11-21 11:37 UTC, mosem commented on test_denoiser.py
>      'demucs_hifi': ['train.py', 'dset=valentini_dummy', 'experiment=demucs_hifi',
done.

2021-11-24 12:42 UTC, mosem commented on conf/experiment/demucs_skipless_adversarial_1.yaml
> +experiment_name: demucs_skipless_adversarial_1
done.

2021-11-24 12:43 UTC, mosem commented on denoiser/models/demucs_encoder.py
> +            return std * x
done. implemented in autoencoder_decomposer.py

2021-11-24 12:44 UTC, mosem commented
Are the new changes satisfactory enough to approve?

2021-11-25 08:43 UTC, merged