Add demucs with transformer 2
mosem/denoiser pull request #32
Opened 2021-11-09 13:34 UTC by mosem

2021-11-15 17:21 UTC, Or-Tal requested changes
could you split to several pull requests? I can't follow this in a reasonable time

2021-11-18 18:57 UTC, Or-Tal requested changes
Hi, Please see comments

2021-11-18 18:57 UTC, Or-Tal commented on conf/config.yaml
>  # Hydra config
this should match master's main_config

2021-11-18 18:57 UTC, Or-Tal commented on conf/experiment/demucs_skipless_1.yaml
> +experiment_name: demucs_skipless_1
lacking #@package

2021-11-18 18:57 UTC, Or-Tal commented on conf/experiment/demucs_skipless_adversarial_1.yaml
> +experiment_name: demucs_skipless_adversarial_1
lacking #@package

2021-11-18 18:57 UTC, Or-Tal commented on conf/experiment/demucs_with_transformer_1.yaml
> +experiment_name: demucs_with_transformer_1
lacking #@package

2021-11-18 18:57 UTC, Or-Tal commented on conf/experiment/demucs_with_transformer_adversarial_1.yaml
> +experiment_name: demucs_with_transformer_adversarial_1
lacking #@Package

2021-11-18 18:57 UTC, Or-Tal commented on denoiser/models/autoencoder_composer.py
> +    def forward(self, signal):
to my opinion, the whole normalization should be dealt with in this function, same for re-multiplying the output by std.

2021-11-18 18:57 UTC, Or-Tal commented on test_denoiser.py
> +                'experiment.segment=2', 'experiment.stride=2','ddp=0', 'experiment.scale_factor=2',
demucs hifi should not be here.. it's my bad but could you please delete it?

2021-11-24 12:45 UTC, mosem commented on conf/config.yaml
>  # Hydra config
merged with master. done.

2021-11-24 12:46 UTC, mosem commented on denoiser/models/autoencoder_composer.py
> +    def forward(self, signal):
done.

2021-11-24 12:49 UTC, mosem commented on test_denoiser.py
> +                'experiment.segment=2', 'experiment.stride=2','ddp=0', 'experiment.scale_factor=2',
done. shouldn't we remove other code as well? such as in batch_solver_factory.py, hifi_gan_loss_functions,py,  demucs_hifi_generator.py, and demucs_hifi_bs.py?

2021-11-25 08:45 UTC, Or-Tal commented on test_denoiser.py
> +                'experiment.segment=2', 'experiment.stride=2','ddp=0', 'experiment.scale_factor=2',
will do in a separate pull request

2021-11-25 09:18 UTC, merged